services:
  db:
    image: postgres:latest
    container_name: your_lastname_postgres
    environment:
      POSTGRES_USER: eleonora
      POSTGRES_PASSWORD: 1003
      POSTGRES_DB: grischenko
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eleonora"]
      interval: 10s
      timeout: 5s
      retries: 5

  python-app:
    build: ./python-app
    container_name: python_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=eleonora
      - POSTGRES_PASSWORD=1003
      - POSTGRES_DB=grischenko
      - POSTGRES_HOST=db
    links:
      - db

